accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like')
              ]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from articleapp.views import ArticleListView

urlpatterns = [
                  path('', TemplateView.as_view(template_name='index.html'), name='home'),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('intro/', include('introapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribe/', include('subscribapp.urls')),
                  path('questions/', include('questionapp.urls')),
                  path('products/', include('productapp.urls')),
                  path('likes/', include('likeapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
        path('create/', ProfileCreateView.as_view(), name='create'),
        path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

class helloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

class HelloWorld2(models.Model):
    text = models.CharField(max_length=100, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import helloWorld
from articleapp.models import Article


@login_required
def hello_world(request):
    # if request.user.is_authenticated:
    if request.method == 'POST':
        new_hello_world = helloWorld()
        new_hello_world.text = request.POST.get('hello_world_input')
        new_hello_world.save()

        hello_world_list = helloWorld.objects.all()

        return HttpResponseRedirect(reverse('introapp:intro'))
    else:
        hello_world_list = helloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_output': hello_world_list})
# else:
#     return HttpResponseRedirect(reverse('accountapp:login'))

has_ownership = [account_ownership_required, login_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    paginate_by =25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        object_list = object_list.order_by('-id')
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)



@method_decorator(has_ownership, 'post')
@method_decorator(has_ownership, 'get')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'post')
@method_decorator(has_ownership, 'get')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">


    <div style="text-align: center; max-width: 300px; margin:auto ">

        <h1>
            sign-up
        </h1>

        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">

        </form>

    </div>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">
        <br>
        <br>
        <br>
        <br>
        <h3>
            계정 삭제
        </h3>
        <br>
        <br>
        <p> "There is nothing noble in being superior to your fellow man;</p>
        <p>true nobility is being superior to your former self.”</p>
        <p>- Ernest Hemingway - </p>




        <br>
        <br>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-12 mt-3">
            <br>
            <br>
        </form>

    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block contents %}


    <style>

        .container {
            padding: 0;
            margin: auto;
        }

        .container div {
            width: 150px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
        }

        .container a {
            width: 45%;
            max-width: 250px;
        }

        .container img {
            width: 100%;
            height: 100%;
            border-radius: 1rem;

        }

        .container .item1 {
            height: 200px;
        }

        .container .item4 {
            height: 800px;
        }

        .container .item6 {
            height: 600px;
        }

        .container .item11 {
            height: 400px;
        }


    </style>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <div style="text-align: center; margin: 4rem auto">
        <div>

            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" alt=""
                     style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;"
                >
                <div>
                    <h2 style="margin-left: 0; padding-left: 43rem; text-align: left">
                        <span class="material-icons">fingerprint</span>
                        : {{ target_user.profile.nickname }}
                    </h2>
                    <h5  style="margin-left: 0; padding-left: 43rem; text-align: left; font-size: 1rem;">
                        <span class="material-icons" style="margin-right: 0.5rem">edit_note</span>
                        : {{ target_user.profile.message }}
                    </h5>
                </div>

                <hr>
                {% if target_user == user %}

                    <a href="{% url 'articleapp:create' %}" class="btn btn-success rounded-pill"
                       style="margin-right: 2rem;">
                        article create
                    </a>


                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                       class="btn btn-primary rounded-pill" style="margin-right: 2rem;">
                        profile update
                    </a>

                {% endif %}
            {% else %}

                {% if target_user == user %}

                    <a href="{% url 'profileapp:create' %}" class="btn btn-dark rounded-pill"
                       style="margin-right: 2rem;">
                        profile create
                    </a>



                {% endif %}


            {% endif %}

            {% if target_user == user %}



                <a href="{% url 'accountapp:update' pk=user.pk %}" class="btn btn-dark rounded-pill"
                   style="margin-right: 2rem;">
                    <span>account update </span>
                </a>



                <a href=" {% url 'accountapp:delete' pk=user.pk %}" class="btn btn-danger rounded-pill">
                    <span>
                        delete
                    </span>
                </a>
                <br>
            {% endif %}

        </div>


    </div>


    <div>
        {% include 'snippets/List_pragmatic.html' with article_list=object_list %}
    </div>
{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}


{% block contents %}




    <div style="text-align: center">
        <h1>
            hello world list
        </h1>

        <form action="/accounts/hello_world/" method="POST">
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <br>
            <div>
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_output %}
            {% for i in hello_world_output %}
                <h4>
                    {{ i.text }}
                </h4>
            {% endfor %}
        {% endif %}

    </div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% block contents %}
{% load bootstrap4 %}

    <div style="text-align: center">
    <h3> Login </h3>
    </div>

    <div style="text-align: center; max-width: 500px; margin: 4rem auto  " >
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {%   bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">
        <div class="'mb-4">
            <h4>change info</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">

        </form>

    </div>

{% endblock %}