articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like')
              ]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from articleapp.views import ArticleListView

urlpatterns = [
                  path('', TemplateView.as_view(template_name='index.html'), name='home'),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('intro/', include('introapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribe/', include('subscribapp.urls')),
                  path('questions/', include('questionapp.urls')),
                  path('products/', include('productapp.urls')),
                  path('likes/', include('likeapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    like = models.IntegerField(default=0)

articleapp/forms.py
from django.forms import ModelForm, forms
from django import forms
from articleapp.models import Article

class ArticleCreationForm(ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'



@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'


    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})



@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'
    success_url = reverse_lazy('articleapp:list')

class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 30

    def get_queryset(self):
        article_list = Article.objects.order_by('-id')
        return article_list

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">

         <h1>
            Article create
         </h1>

        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">

        </form>

    </div>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">

         <h3>
           Delete Article : {{ target_article.title }}
         </h3>

        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-12 mt-3">
        </form>

    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
{% block contents %}


    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h3 style="font-weight: bold">
                {{ target_article.title }}
            </h3>
            <div style="height: 2rem">
                <a href="{% url 'likeapp:article_like' pk=target_article.pk %}"> <i
                        style="vertical-align: middle; font-size: 1.2rem; color: #f77" class="material-icons">
                    favorite
                </i>
                </a>
                <span style="vertical-align: middle;  font-size: 1.2rem;">{{ target_article.like }}</span>
            </div>

            <h5>
                writer : {{ target_article.writer.profile.nickname }}
            </h5>
        <br>

            <hr>
            <img style=" border-radius:1rem; width: 25rem;" src="{{ target_article.image.url }}" alt="">
        <br>
                <br>
            <p>
                {{ target_article.content }}
            </p>

            {% if target_article.writer == user %}

                <p>
                    <a href="{% url 'articleapp:create' %}" class="btn btn-success rounded-pill">
                        article create
                    </a>
                </p>

                <p>
                    <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-primary rounded-pill">
                        article update
                    </a>
                </p>
                <p>
                    <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger rounded-pill">
                        article delete
                    </a>
                </p>
            {% endif %}
            <hr>
            <p>
                <a href="{% url 'articleapp:list' %}" style="width: 20rem; color: #2f6f9f" >
                    back
                </a>
            </p>
        </div>
    </div>
    <div id="disqus_thread"></div>
    <script>
        /**
         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://test1-gqabuqqpcd.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>


    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/614d881dd326717cb6831bea/1fi25vvlj';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}


    <style>

        .container {
            padding: 0;
            margin: auto;
        }

        .container div {
            width: 150px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 1rem;
        }

        .container a {
            width: 45%;
            max-width: 250px;
        }

        .container img {
            width: 100%;
            height: 100%;
            border-radius: 1rem;

        }

        .container .item1 {
            height: 200px;
        }

        .container .item4 {
            height: 800px;
        }

        .container .item6 {
            height: 600px;
        }

        .container .item11 {
            height: 400px;
        }


    </style>

    <div style="text-align: center; width: 100%; ">
        <a href="{% url 'articleapp:create' %}" class="btn btn-success rounded-pill col-3 mt-3 mb-3">
            Article Create
        </a>
    </div>

    <br>
    <br>
    <div style="margin: auto">
        {% if article_list %}
            <div class="container">
                {% for article in article_list %}
                    <a href="{% url 'articleapp:detail' pk=article.pk %}" style=" max-width: 180px">
                        {% include 'snippets/card.html' with article=article %}
                        <h5 style="font-weight: bold">  {{ article.title | truncatechars:10 }}
                            <i style="margin-left: 3rem; vertical-align: middle; font-size: 0.7rem; color: #f77" class="material-icons">favorite</i>
                            <span style="vertical-align: middle; font-size: 0.7rem;">{{ article.like }}</span></h5>
                        <h6>  {{ article.writer.profile.nickname }}

                        </h6>
                    </a>

                {% endfor %}
            </div>
            <script src="{% static 'js/magicgrid.js' %}"></script>

        {% else %}
            <div style="text-align: center">
                <h1> No articles Yet !</h1>
            </div>
        {% endif %}

        {% include 'snippets/pagination.html' with page_obj=page_obj %}

    </div>
    <!--Start of Tawk.to Script-->

    <!--End of Tawk.to Script-->
{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">

         <h1>
            Article update
         </h1>

        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">

        </form>

    </div>

{% endblock %}