accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like')
              ]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from articleapp.views import ArticleListView

urlpatterns = [
                  path('', TemplateView.as_view(template_name='index.html'), name='home'),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('intro/', include('introapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribe/', include('subscribapp.urls')),
                  path('questions/', include('questionapp.urls')),
                  path('products/', include('productapp.urls')),
                  path('likes/', include('likeapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionapp/urls.py
from django.urls import path

from questionapp.views import QuestionCreateView, QuestionDetailView, QuestionListView, QuestionDeleteView
from . import views

app_name = 'questionapp'

urlpatterns = [
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('detail/<int:pk>', QuestionDetailView.as_view(), name='detail'),
    path('list/', QuestionListView.as_view(), name='list'),
    path('delete/<int:pk>', QuestionDeleteView.as_view(), name='delete'),
    path('search/', views.SearchFormView.as_view(), name='search'),
]

questionapp/models.py
import os

from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Question(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='question')
    title = models.CharField(max_length=200, null=True)
    image = models.FileField(upload_to='question/', null=True, blank=True)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    question_hit = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title


    def get_file_name(self):
        return os.path.basename(self.image.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    @property
    def test_123(self):
        self.question_hit += 1
        self.save()

questionapp/forms.py
from django.forms import ModelForm, forms
from questionapp.models import Question
from django import forms


class QuestionCreationForm(ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'image', 'content']


class QuestionSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

questionapp/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms import forms
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, FormView
from questionapp.decorators import question_ownership_required
from questionapp.forms import QuestionCreationForm, QuestionSearchForm
from questionapp.models import Question


@method_decorator(login_required, 'post')
@method_decorator(login_required, 'get')
class QuestionCreateView(CreateView):
    model = Question
    form_class = QuestionCreationForm
    template_name = 'questions/create.html'

    # 게시글 작성자의 writer를 저장
    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('questionapp:detail', kwargs={'pk': self.object.pk})


class QuestionDetailView(DetailView):
    model = Question
    context_object_name = 'target_question'
    template_name = 'questions/detail.html'


class QuestionListView(ListView):
    model = Question
    context_object_name = 'question_list'
    template_name = 'questions/list.html'
    paginate_by = 30

    def get_queryset(self):
        article_list = Question.objects.order_by('-id')
        return article_list

    def get(self, *args, **kwargs):
        return super(QuestionListView, self).get(self, *args, **kwargs)

    # def search(request):
    #      question_list = Question.objects.order_by('-id')
    #      q = request.POST.get('q', "")
    #
    #      if q:
    #         question_list = question_list.filter(title__icontains=q)
    #         return render(request, 'questions/list.html', {'question_list': question_list, 'q': q})
    #      else:
    #          return render(request, 'questions/list.html')



@method_decorator(question_ownership_required, 'get')
@method_decorator(question_ownership_required, 'post')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'target_question'
    template_name = 'questions/delete.html'
    success_url = reverse_lazy('questionapp:list')


class SearchFormView(FormView):
    template_name = 'questions/search.html'
    form_class = QuestionSearchForm

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        question_list = Question.objects.all().filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) |
                                               Q(content__icontains=searchWord)).distinct()

        context = { }
        context['form'] = form
        context['search_term'] = searchWord
        context['question_list'] = question_list

        return render(self.request, self.template_name, context)

questionapp/templates/questions/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:2rem auto auto auto">

        <h3>
            <button type="button" class="btn btn-outline-secondary"> Question Create</button>
        </h3>
        <br>

        <form action="{% url 'questionapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">
        </form>

    </div>

{% endblock %}

questionapp/templates/questions/delete.html
{% extends 'base.html' %}
{% block contents %}

    <div style="text-align: center; max-width: 550px; margin:auto ">
        <br>
        <br>
        <h5>
            {{ target_question.title }}
        </h5>

        <br>
        <br>

        <p>삭제된 글은 데이터가 서버에서도 영구 삭제되어 복구가 불가능합니다. </p>
            <p>아래 제출을 누루면 삭제 됩니다.</p>

        <form action="{% url 'questionapp:delete' pk=target_question.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-12 mt-3">
        </form>

    </div>

{% endblock %}

questionapp/templates/questions/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <br>
    <h5 class="card-title" style=" text-align: center; font-weight: bold">
        {{ target_question.title }}</h5>
    <br>



    <div style="text-align: center;  margin-left:27.5rem; ">

        <div class="card" style="width: 40rem;">
            <div class="card-body">
                <p class="card-text">
                    {{ target_question.content }}
                </p>
                {% if target_question.image %}

                    <a href="{{ target_question.image.url }}" class="btn btn-outline-dark" role="button">
                           <i class="material-icons" style="margin-right: 2rem; vertical-align: middle">
                        cloud_upload
                    </i> DownLoad</a>
                {% endif %}
                <hr>
                <a href="{% url 'questionapp:create' %}" class="card-link">Create</a>
                <a href="{% url 'questionapp:delete' pk=target_question.pk %}" class="card-link" style="color: darkred">Delete</a>
            </div>
        </div>


    </div>
    <br>
    <div style="text-align: center">
        <a href="{% url 'questionapp:list' %}" class="btn btn-primary rounded-pill mt-3">
            Question List로 가기
        </a>
    </div>
    <div id="disqus_thread"></div>

    <script>
        /**
         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://test1-gqabuqqpcd.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>


    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>



{% endblock %}

questionapp/templates/questions/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; margin: 3rem 0; ">
        <h2 style="font-family: 'Quicksand', sans-serif;"> Q & A </h2>
    </div>
    <table class="table" style=" width: 50rem; margin:auto auto 5rem auto; text-align: center">
        <thead>
        <tr>
            <th>No.</th>
            <th>title</th>
            <th>writer</th>
            <th>file</th>
            <th>hit</th>
            <th>date</th>


        </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list %}
                <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'questionapp:detail' pk=question.pk %}"> {{ question.title | truncatechars:40 }}  </a>
                </td>
                <td> {{ question.writer.profile.nickname }} </td>

                <td> {% if question.image %}
                    <i class="material-icons">
                        cloud_upload
                    </i>
                {% endif %}
                </td>
                <td>  {{ question.test_123 }} </td>
                <td><p style="font-size: 0.7rem; padding: 0.3rem"> {{ question.created_at }} </p></td>


            {% endfor %}
        {% endif %}
        </tbody>
    </table>


    <div style="text-align: center">
        <a href="{% url 'questionapp:create' %}" class="btn btn-success rounded-pill mt-3">
            질문 남기기
        </a>

    </div>

{% endblock %}

questionapp/templates/questions/search.html
{% extends "base.html" %}


{% block content %}
<h1>Blog Search</h1>
<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }} <!-- form을 테이블 형식으로 표시, 여기서 form은 views에서 넘겨준 PostSearchForm 객체임-->
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br/><br/>

{% if object_list %}
    {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}
{% elif search_term %}<!-- 검색란이 공란인지 확인-->
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}

questionapp/templates/questions/test.html
<table class="table">
    <thead>
    <tr>
        <th>제목</th>
        <th>작성자</th>
    </tr>
    </thead>
    <tbody>
    {% if question_list %}
        {% for question in question_list %}
            <div style="margin-left: 15rem;">

                <div class="card" style="width: 60rem;">

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'questionapp:detail' pk=question.pk %}">
                                <span class="badge rounded-pill bg-secondary"> {{ question.created_at }}</span>
                                {{ question.title | truncatechars:40 }}
                                <span class="badge bg-info text-dark"
                                      style="font-size: 0.7rem;">작성자 : {{ question.writer.profile.nickname }}</span>
                                <span class="badge bg-info text-dark"
                                      style="font-size: 0.7rem;">hits : {{ question.test_123 }}</span>

                            </a>
                        </li>
                    </ul>
                </div>


                <br>


            </div>
        {% endfor %}
    {% endif %}


    </tbody>
</table>

questionapp/templates/questions/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}

    <div style="text-align: center; max-width: 300px; margin:auto ">

         <h1>
            Question update
         </h1>

        <form action="{% url 'questionapp:update' pk=target_question.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill mt-3">

        </form>

    </div>

{% endblock %}